name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey there! Thanks for disclosing an issue, please make sure to have it as detailed as possible to help our devs!'
        pr-message: 'Hey there! Thanks for opening a PR, please make sure to have it as detailed as possible, and is thoroughly tested to help the progress of Scarlet!'
